apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: stonesoup1-xcgv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: stonesoup1-xcgv
    app.kubernetes.io/part-of: ricks-stonesoup1
  name: stonesoup1-xcgv
  namespace: rhn-support-rick-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: stonesoup1-xcgv
    weight: null
status: {}
